apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "motaraireh/mywebapp:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mykustom-map
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"bases:
resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1
patches:
 - replicas.yaml

configMapGenerator:
- name: mykustom-map
  env: config.properties
