#bases:
#- ../../base

#patches:
# - replicas.yaml

#configMapGenerator:
#- name: mykustom-map
#  env: config.properties


# Example of kustomization.yaml content
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - replicas.yaml
configMapGenerator:
  - name: mykustom-map
    env: config.properties
